-- Oracle DB Schema for Smart Habit Tracker
-- Run these commands in SQL*Plus, SQL Developer, or your Oracle client

-- Create Users table
CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR2(255) UNIQUE NOT NULL,
  password_hash VARCHAR2(255) NOT NULL,
  name VARCHAR2(200),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Create Tasks table
CREATE TABLE tasks (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER REFERENCES users(id),
  title VARCHAR2(400) NOT NULL,
  description VARCHAR2(2000),
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP,
  priority VARCHAR2(20) DEFAULT 'MEDIUM',
  state VARCHAR2(20) DEFAULT 'NEW',
  completed NUMBER(1) DEFAULT 0,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Insert sample user
INSERT INTO users (email, password_hash, name) 
VALUES ('test@example.com', '$2b$10$hash', 'Test User');

-- Insert sample tasks
INSERT INTO tasks (title, description, priority, state) 
VALUES ('Morning Exercise', 'Run 3km', 'HIGH', 'NEW');

INSERT INTO tasks (title, description, priority, state) 
VALUES ('Read Book', 'Read 20 pages', 'MEDIUM', 'IN_PROGRESS');

COMMIT;
