const oracledb = require('oracledb');
require('dotenv').config();

async function setupDatabase() {
  let connection;
  try {
    // Create connection directly (not using pool)
    connection = await oracledb.getConnection({
      user: process.env.ORACLE_USER,
      password: process.env.ORACLE_PASSWORD,
      connectString: process.env.ORACLE_CONNECTION_STRING
    });

    console.log('✓ Connected to Oracle Database');

    // Drop existing tables (optional, for fresh start)
    try {
      await connection.execute('DROP TABLE tasks');
      console.log('✓ Dropped existing tasks table');
    } catch (err) {
      // Table doesn't exist, that's fine
    }

    try {
      await connection.execute('DROP TABLE users');
      console.log('✓ Dropped existing users table');
    } catch (err) {
      // Table doesn't exist, that's fine
    }

    // Create Users table
    await connection.execute(`
      CREATE TABLE users (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR2(255) UNIQUE NOT NULL,
        password_hash VARCHAR2(255) NOT NULL,
        name VARCHAR2(200),
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP
      )
    `);
    console.log('✓ Created users table');

    // Create Tasks table
    await connection.execute(`
      CREATE TABLE tasks (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER REFERENCES users(id),
        title VARCHAR2(400) NOT NULL,
        description VARCHAR2(2000),
        created_date TIMESTAMP DEFAULT SYSTIMESTAMP,
        priority VARCHAR2(20) DEFAULT 'MEDIUM',
        state VARCHAR2(20) DEFAULT 'NEW',
        completed NUMBER(1) DEFAULT 0,
        updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
      )
    `);
    console.log('✓ Created tasks table');

    // Commit changes
    await connection.commit();
    console.log('\n✓ Database setup completed successfully!');

  } catch (err) {
    console.error('✗ Error setting up database:', err.message);
    process.exit(1);
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

setupDatabase();
